//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsw2026Tpi.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dsw2026Tpi.CrossCutting.Resources.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos.
        /// </summary>
        public static string AUTHENTICATION_FAILED {
            get {
                return ResourceManager.GetString("AUTHENTICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requieren permisos para la operación solicitada.
        /// </summary>
        public static string AUTHORIZATION_FAILED {
            get {
                return ResourceManager.GetString("AUTHORIZATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción debe tener entre 11 y 100 caracteres.
        /// </summary>
        public static string DESCRIPTION_ERROR {
            get {
                return ResourceManager.GetString("DESCRIPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El médico ya está eliminado.
        /// </summary>
        public static string DOCTOR_INACTIVE {
            get {
                return ResourceManager.GetString("DOCTOR_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La matrícula ingresada ya existe.
        /// </summary>
        public static string DUPLICATE_LICENSE_ERROR {
            get {
                return ResourceManager.GetString("DUPLICATE_LICENSE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción no puede ser vacía.
        /// </summary>
        public static string EMPTY_DESCRIPTION_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_DESCRIPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar un nombre .
        /// </summary>
        public static string EMPTY_NAME_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_NAME_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entidad {0} no se encontró.
        /// </summary>
        public static string ENTITY_NOTFOUND {
            get {
                return ResourceManager.GetString("ENTITY_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cancelar la cita si no está reservada.
        /// </summary>
        public static string INVALID_APPOINTMENT_ERROR {
            get {
                return ResourceManager.GetString("INVALID_APPOINTMENT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cita ya fue cancelada.
        /// </summary>
        public static string INVALID_APPOINTMENT_STATUS {
            get {
                return ResourceManager.GetString("INVALID_APPOINTMENT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Día de la semana no válido.
        /// </summary>
        public static string INVALID_DAY_ERROR {
            get {
                return ResourceManager.GetString("INVALID_DAY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI no es válido.
        /// </summary>
        public static string INVALID_DNI_ERROR {
            get {
                return ResourceManager.GetString("INVALID_DNI_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La razón debe contener más de 5 caracteres.
        /// </summary>
        public static string INVALID_REASON_ERROR {
            get {
                return ResourceManager.GetString("INVALID_REASON_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tiempo de inicio debe ser anterior al tiempo de finalización.
        /// </summary>
        public static string INVALID_TIME_CONFLICT {
            get {
                return ResourceManager.GetString("INVALID_TIME_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de licencia no puede ser vacio.
        /// </summary>
        public static string LICENSE_ERROR {
            get {
                return ResourceManager.GetString("LICENSE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe tener entre 3 y 100 caracteres.
        /// </summary>
        public static string NAME_ERROR {
            get {
                return ResourceManager.GetString("NAME_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El turno está en una fecha pasada.
        /// </summary>
        public static string PAST_DATE_CONFLICT {
            get {
                return ResourceManager.GetString("PAST_DATE_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al registrar el usuario.
        /// </summary>
        public static string REGISTER_USER_CONFLICT {
            get {
                return ResourceManager.GetString("REGISTER_USER_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de registración de usuario no válidos.
        /// </summary>
        public static string REGISTER_USER_INVALID {
            get {
                return ResourceManager.GetString("REGISTER_USER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El turno no está disponible.
        /// </summary>
        public static string SLOT_NOT_AVAILABLE_CONFLICT {
            get {
                return ResourceManager.GetString("SLOT_NOT_AVAILABLE_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las disponibilidades no pueden solaparse.
        /// </summary>
        public static string SOLAPAMIENTO_CONFLICT {
            get {
                return ResourceManager.GetString("SOLAPAMIENTO_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La especialidad ya existe.
        /// </summary>
        public static string SPECIALITY_EXISTS {
            get {
                return ResourceManager.GetString("SPECIALITY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La especialidad ya está eliminada.
        /// </summary>
        public static string SPECIALITY_INACTIVE {
            get {
                return ResourceManager.GetString("SPECIALITY_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tiempo de inicio del turno no puede ser mayor o igual al tiempo de finalización.
        /// </summary>
        public static string START_TIME_ERROR {
            get {
                return ResourceManager.GetString("START_TIME_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error no controlado.
        /// </summary>
        public static string UNHANDLED_ERROR {
            get {
                return ResourceManager.GetString("UNHANDLED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uno o más errores de validación ocurrieron.
        /// </summary>
        public static string VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR", resourceCulture);
            }
        }
    }
}
